### ISSUE TITLE
`optimal-congress` crashes with `SyntaxError: f-string: unmatched '('` in `optimize.py`, line 53

### ISSUE THREAD

**Issue by dreirund** [top-on/optimal-congress#1] opened 2023-12-21 18:02 UTC
Ahoj,

I build and install this software as an [&nearr;&hairsp;Arch Linux package](https://aur.archlinux.org/packages/optimal-congress-git); to do so I build it using  
`python -m build --wheel --no-isolation`  
and then package it using  
`python -m installer --destdir="${pkgdir}" dist/*.whl`  
(where `${pkgdir}` is a temporary directory that then the packaging script reads and builds into a distribution package.)

When I then install the package and run `optimal-congress` or `optimal-congress fetch`, it fails with `SyntaxError: f-string: unmatched '('`:  
```
Traceback (most recent call last):
  File "/usr/bin/optimal-congress", line 5, in <module>
    from optimal_congress.cli import app
  File "/usr/lib/python3.11/site-packages/optimal_congress/cli.py", line 19, in <module>
    from optimal_congress.optimize import optimize_schedule
  File "/usr/lib/python3.11/site-packages/optimal_congress/optimize.py", line 53
    f"overlap_{str(event_i.id).replace("-", "_")}"
                                        ^
SyntaxError: f-string: unmatched '('
```

Regards!

**Comment by top-on** [comment] 2023-12-21 22:06
thanks for noticing this issue, @dreirund !

the issue seems to be due to me only having tested the releases on python 3.12.
i think it's due to the new [f-string capabilities](https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-pep701) that having `.replace` inside the f-string's curly braces works with 3.12.

as an example, the following works in python 3.12, but not in 3.11:
```python
>>> f"{'-_-'.replace("-", "_")}"
```
in fact, in python 3.11 this throws the familiar `SyntaxError: f-string: unmatched '('`.

so as a quick fix, you can try building the package with python 3.12.

and i will make sure to soon have removed the fancy f-string syntax, to be compatible with all the python versions that are claimed to work in `pyproject.toml`.

**Comment by top-on** [comment] 2023-12-21 22:59
@dreirund , could you please check if the issue is resolved by [release 0.5.1](https://github.com/top-on/optimal-congress/releases/tag/0.5.1)?

**Comment by dreirund** [comment] 2023-12-21 23:23
> @dreirund , could you please check if the issue is resolved by
> [release
> 0.5.1](https://github.com/top-on/optimal-congress/releases/tag/0.5.1)?

I just built again with latest git checkout, issue resolved.

However I see that you have hard-coded a colour scheme that is not well
visible on black-on-white terminals. Can you include some way to make
it compatible with light terminal colour schemes?, e.g.

* by allowing to specify the colour scheme,
* by allowing a non-coloured version,
* by autodetecting (I don't know if it is possible) the terminal
  colours?

Regards!

**Comment by top-on** [comment] 2023-12-22 15:11
thanks for confirming that this works, now.
closing this issue, and continuing the point on color in #2 .

**Closed as completed by top-on** 2023-12-22 15:11 UTC
